//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public System.Guid Id { get; set; }
        public System.Guid ClientId { get; set; }
        public string Source { get; set; }
        public System.DateTimeOffset DateStartUTC { get; set; }
        public Nullable<System.DateTimeOffset> DateEndUTC { get; set; }
        public System.Guid Role { get; set; }
        public System.Guid RefreshTokenId { get; set; }
    
        public virtual RefreshToken RefreshToken { get; set; }
    }
}
