//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataField
    {
        public DataField()
        {
            this.MetaData = new HashSet<MetaData>();
        }
    
        public System.Guid DataFieldId { get; set; }
        public string DataFieldReference { get; set; }
        public System.Guid TypeDocumentId { get; set; }
        public bool DataFieldMandatory { get; set; }
        public string DataFieldType { get; set; }
        public System.Guid EntityId { get; set; }
        public System.Guid UserCreateData { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
        public Nullable<System.Guid> UserUpdateData { get; set; }
        public Nullable<System.DateTimeOffset> DateUpdateData { get; set; }
        public Nullable<System.Guid> UserDeleteData { get; set; }
        public Nullable<System.DateTimeOffset> DateDeleteData { get; set; }
        public bool EtatDeleteData { get; set; }
    
        public virtual Type_Document Type_Document { get; set; }
        public virtual ICollection<MetaData> MetaData { get; set; }
    }
}
