//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataFieldAutoComplete
    {
        public System.Guid DataFieldId { get; set; }
        public int DataFieldAutoCompleteIndex { get; set; }
        public string DataFieldAutoCompleteReference { get; set; }
        public string DataFieldAutoCompleteUrl { get; set; }
        public string DataFieldAutoCompletePlaceHolder { get; set; }
        public string DataFieldAutoCompleteTitle { get; set; }
        public System.Guid EntityId { get; set; }
        public System.Guid UserCreateData { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
        public Nullable<System.Guid> UserUpdateData { get; set; }
        public Nullable<System.DateTimeOffset> DateUpdateData { get; set; }
        public Nullable<System.Guid> UserDeleteData { get; set; }
        public Nullable<System.DateTimeOffset> DateDeleteData { get; set; }
        public bool EtatDeleteData { get; set; }
    
        public virtual DataField DataField { get; set; }
    }
}
