//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Version = new HashSet<Version>();
            this.MetaData = new HashSet<MetaData>();
        }
    
        public System.Guid DocumentId { get; set; }
        public string DocumentReference { get; set; }
        public System.Guid DocumentSatutId { get; set; }
        public Nullable<System.Guid> DocumentCurrentVersion { get; set; }
        public System.Guid EntityId { get; set; }
        public System.Guid UserCreateData { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
        public Nullable<System.Guid> UserUpdateData { get; set; }
        public Nullable<System.DateTimeOffset> DateUpdateData { get; set; }
        public Nullable<System.Guid> UserDeleteData { get; set; }
        public Nullable<System.DateTimeOffset> DateDeleteData { get; set; }
        public bool EtatDeleteData { get; set; }
        public string DocumentLabel { get; set; }
        public System.Guid DocumentTypeId { get; set; }
    
        public virtual StatutDocument Statut_Document { get; set; }
        public virtual ICollection<Version> Version { get; set; }
        public virtual TypeDocument Type_Document { get; set; }
        public virtual ICollection<MetaData> MetaData { get; set; }
    }
}
