//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentStatusHisto
    {
        public System.Guid DocumentId { get; set; }
        public int DocumentIndex { get; set; }
        public System.Guid DocumentStatusId { get; set; }
        public System.Guid EntityId { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
        public System.Guid UserCreateData { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual UserTk UserTk { get; set; }
    }
}
