//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTk
    {
        public System.Guid GroupTkId { get; set; }
        public string GroupTkReference { get; set; }
        public string GroupTkLabel { get; set; }
        public System.Guid GroupTkEntityId { get; set; }
    }
}
