//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public System.Guid PageId { get; set; }
        public string PageReference { get; set; }
        public Nullable<System.Guid> PageStreamId { get; set; }
        public System.Guid PageVersionId { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
        public System.Guid EntityId { get; set; }
        public System.Guid UserCreateData { get; set; }
        public Nullable<System.DateTimeOffset> DateUpdateData { get; set; }
        public Nullable<System.Guid> UserDeleteData { get; set; }
        public Nullable<System.DateTimeOffset> DateDeleteData { get; set; }
        public Nullable<System.Guid> UserUpdateData { get; set; }
        public bool EtatDeleteData { get; set; }
        public int PageNumber { get; set; }
    }
}
