//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public RefreshToken()
        {
            this.AccessToken = new HashSet<AccessToken>();
        }
    
        public System.Guid Id { get; set; }
        public string ClientId { get; set; }
        public System.Guid UserTkId { get; set; }
        public string Source { get; set; }
        public System.DateTimeOffset DateStartUTC { get; set; }
        public Nullable<System.DateTimeOffset> DateEndUTC { get; set; }
        public System.Guid Role { get; set; }
    
        public virtual GroupTk GroupTk { get; set; }
        public virtual UserTk UserTk { get; set; }
        public virtual ICollection<AccessToken> AccessToken { get; set; }
    }
}
