//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTk
    {
        public System.Guid UserTkId { get; set; }
        public string UserTkReference { get; set; }
        public string UserTkLastName { get; set; }
        public string UserTkFirstName { get; set; }
        public string UserTkLogin { get; set; }
        public string UserTkPassword { get; set; }
        public bool UserTkExternalAccount { get; set; }
        public string UserTkEmail { get; set; }
    }
}
