//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public Version()
        {
            this.Page = new HashSet<Page>();
        }
    
        public System.Guid VersionId { get; set; }
        public string VersionReference { get; set; }
        public Nullable<System.Guid> VersionStreamId { get; set; }
        public System.Guid VersionStatutId { get; set; }
        public System.Guid VersionDocumentId { get; set; }
        public bool VersionMajor { get; set; }
        public decimal VersionNumber { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
        public Nullable<System.Guid> EntityId { get; set; }
        public Nullable<System.Guid> UserCreateData { get; set; }
        public Nullable<System.DateTimeOffset> DateUpdateData { get; set; }
        public Nullable<System.Guid> UserDeleteData { get; set; }
        public Nullable<System.DateTimeOffset> DateDeleteData { get; set; }
        public Nullable<System.Guid> UserUpdateData { get; set; }
        public bool EtatDeleteData { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ICollection<Page> Page { get; set; }
        public virtual StatutVersion Statut_Version { get; set; }
    }
}
