//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserEntity
    {
        public System.Guid EntityId { get; set; }
        public System.Guid UserTkId { get; set; }
        public string EntityReference { get; set; }
        public string EntityLibelle { get; set; }
        public bool EtatDeleteData { get; set; }
    }
}
