//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TypeDocumentDataField
    {
        public System.Guid TypeDocumentId { get; set; }
        public System.Guid FieldId { get; set; }
        public int DisplayIndex { get; set; }
        public bool Mandatory { get; set; }
        public System.Guid EntityId { get; set; }
        public string Label { get; set; }
        public string Reference { get; set; }
        public string TypeId { get; set; }
        public string InputType { get; set; }
        public bool EtatDeleteData { get; set; }
        public string TypeDocumentLabel { get; set; }
        public string EntityReference { get; set; }
        public string EntityLabel { get; set; }
        public int IsList { get; set; }
        public int IsAutocomplete { get; set; }
        public Nullable<System.Guid> DataFieldAutoCompleteId { get; set; }
    }
}
