//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserEntity
    {
        public System.Guid EntityId { get; set; }
        public System.Guid UserTkId { get; set; }
        public string EntityReference { get; set; }
        public string EntityLibelle { get; set; }
        public bool EtatDeleteData { get; set; }
    }
}
