//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DocumentExtended
    {
        public System.Guid EntityId { get; set; }
        public System.Guid DocumentId { get; set; }
        public string DocumentReference { get; set; }
        public string DocumentLabel { get; set; }
        public Nullable<System.Guid> DocumentCurrentVersionId { get; set; }
        public System.Guid DocumentUserCreateData { get; set; }
        public System.DateTimeOffset DocumentDateCreateData { get; set; }
        public bool DocumentEtatDeleteData { get; set; }
        public System.Guid DocumentOwner { get; set; }
        public System.Guid DocumentStatusId { get; set; }
        public string DocumentStatutLabel { get; set; }
        public System.Guid DocumentTypeId { get; set; }
        public string DocumentTypeLabel { get; set; }
        public System.Guid VersionUserCreateData { get; set; }
        public System.DateTimeOffset VersionDateCreateData { get; set; }
        public bool VersionEtatDeleteData { get; set; }
        public bool VersionMajor { get; set; }
        public decimal VersionNumber { get; set; }
        public string VersionReference { get; set; }
        public System.Guid VersionStatusId { get; set; }
        public string VersionStatusLibelle { get; set; }
    }
}
