//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public System.Guid WorkflowId { get; set; }
        public int WorkflowIndex { get; set; }
        public Nullable<System.Guid> WorkflowUserId { get; set; }
        public Nullable<System.Guid> WorkflowTypeDocumentId { get; set; }
        public Nullable<System.DateTimeOffset> WorkflowDateRealize { get; set; }
        public System.Guid WorkflowVersionId { get; set; }
        public System.Guid EntityId { get; set; }
        public System.Guid WorkflowStatusDocumentId { get; set; }
        public System.Guid WorkflowTypeId { get; set; }
        public Nullable<System.Guid> WorkflowAnswerId { get; set; }
        public string WorkflowComment { get; set; }
        public bool EtatDeleteData { get; set; }
        public System.DateTimeOffset DateCreateData { get; set; }
    
        public virtual WorkflowAnswer WorkflowAnswer { get; set; }
    }
}
