//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeDocModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public System.Guid WorkflowId { get; set; }
        public System.Guid WorkFlowTypeId { get; set; }
        public int WorkflowIndex { get; set; }
        public Nullable<System.Guid> WorkflowUserId { get; set; }
        public Nullable<System.Guid> WorkflowTypeDocumentId { get; set; }
        public bool WorkflowRealize { get; set; }
        public Nullable<System.DateTimeOffset> WorkflowDateRealize { get; set; }
        public System.Guid WorkflowVersionId { get; set; }
        public System.Guid EntityId { get; set; }
    
        public virtual TypeDocument Type_Document { get; set; }
        public virtual Version Version { get; set; }
        public virtual WorkflowType WorkflowType { get; set; }
    }
}
